"""Tests for briefing audio generation orchestration."""

from unittest.mock import MagicMock, patch

import pytest

from src.config import Config
from src.services.briefing_audio import (
    BRIEFING_AUDIO_PENDING,
    BRIEFING_AUDIO_READY,
    generate_briefing_audio,
    get_audio_url_or_trigger,
)


@pytest.fixture
def mock_config():
    config = MagicMock(spec=Config)
    config.GEMINI_API_KEY = "test_key"
    config.GEMINI_TTS_MODEL = "gemini-3.1-flash-tts-preview"
    config.GEMINI_TTS_VOICE = "Puck"
    config.GEMINI_MODEL_FLASH = "gemini-2.5-flash"
    config.BRIEFING_AUDIO_SAMPLE_RATE = 24000
    return config


@pytest.fixture
def mock_briefing():
    """A DailyBriefing-like mock with text content but no audio."""
    briefing = MagicMock()
    briefing.id = "briefing-123"
    briefing.headline = "Test Headline"
    briefing.briefing_text = "This is the briefing text."
    briefing.key_themes = ["theme1", "theme2"]
    briefing.episode_highlights = [
        {"podcast_name": "P1", "episode_title": "E1", "analysis": "Good"}
    ]
    briefing.connection_insight = "A connection"
    briefing.audio_status = None
    briefing.audio_data = None
    return briefing


class TestGenerateBriefingAudio:
    def test_already_ready_returns_cached(self, mock_config, mock_briefing):
        """Briefing with audio_status='ready' and audio_data should return ready."""
        mock_briefing.audio_status = "ready"
        mock_briefing.audio_data = b"fake mp3"
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result == BRIEFING_AUDIO_READY
        # Should not claim or generate
        repo.claim_briefing_audio.assert_not_called()

    def test_generating_returns_pending(self, mock_config, mock_briefing):
        """Briefing already being generated by another request."""
        mock_briefing.audio_status = "generating"
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result == BRIEFING_AUDIO_PENDING
        repo.claim_briefing_audio.assert_not_called()

    def test_not_found_returns_none(self, mock_config):
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = None

        result = generate_briefing_audio("missing", repo, mock_config)
        assert result is None

    @patch("src.services.briefing_generator.generate_audio_script")
    @patch("src.services.tts.render_tts_to_mp3")
    def test_successful_generation(self, mock_tts, mock_script, mock_config, mock_briefing):
        mock_script.return_value = "spoken script text"
        mock_tts.return_value = (b"mp3 bytes", 180)
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing
        repo.claim_briefing_audio.return_value = True

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result == BRIEFING_AUDIO_READY
        repo.update_briefing_audio.assert_called_once_with(
            briefing_id="briefing-123",
            audio_data=b"mp3 bytes",
            audio_mime_type="audio/mpeg",
            audio_duration_sec=180,
            status="ready",
        )

    @patch("src.services.briefing_generator.generate_audio_script")
    def test_script_failure_marks_failed(self, mock_script, mock_config, mock_briefing):
        mock_script.return_value = None
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing
        repo.claim_briefing_audio.return_value = True

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result is None
        repo.update_briefing_audio_status.assert_called_once_with(
            "briefing-123", "failed"
        )

    @patch("src.services.briefing_generator.generate_audio_script")
    @patch("src.services.tts.render_tts_to_mp3")
    def test_tts_failure_marks_failed(self, mock_tts, mock_script, mock_config, mock_briefing):
        mock_script.return_value = "spoken script text"
        mock_tts.return_value = (None, None)
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing
        repo.claim_briefing_audio.return_value = True

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result is None
        repo.update_briefing_audio_status.assert_called_once_with(
            "briefing-123", "failed"
        )

    def test_claim_failure_returns_pending(self, mock_config, mock_briefing):
        """Another request claimed the slot between our get and claim."""
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing
        repo.claim_briefing_audio.return_value = False

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result == BRIEFING_AUDIO_PENDING

    @patch("src.services.briefing_generator.generate_audio_script")
    def test_exception_marks_failed(self, mock_script, mock_config, mock_briefing):
        mock_script.side_effect = RuntimeError("boom")
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing
        repo.claim_briefing_audio.return_value = True

        result = generate_briefing_audio("briefing-123", repo, mock_config)
        assert result is None
        repo.update_briefing_audio_status.assert_called_once_with(
            "briefing-123", "failed"
        )


class TestGetAudioUrlOrTrigger:
    def test_ready_returns_url(self, mock_config, mock_briefing):
        mock_briefing.audio_status = "ready"
        mock_briefing.audio_data = b"mp3"
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = mock_briefing

        result = get_audio_url_or_trigger("briefing-123", repo, mock_config)
        assert result["status"] == "ready"
        assert result["audio_url"] == "/api/feed/briefing/briefing-123/audio"

    def test_not_found(self, mock_config):
        repo = MagicMock()
        repo.get_briefing_by_id.return_value = None

        result = get_audio_url_or_trigger("missing", repo, mock_config)
        assert result["status"] == "failed"
        assert result["audio_url"] is None
